# Generated by Django 5.1.3 on 2025-02-13 19:28

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('admin_accesss', models.BooleanField()),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drawings_2d', models.FileField(null=True, upload_to='drawings_2d')),
            ],
        ),
        migrations.CreateModel(
            name='ProducerSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producer_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PWRK', models.CharField(blank=True, max_length=10)),
                ('description_1', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(blank=True, default='NOWY', max_length=30)),
                ('type_of_employee', models.CharField(max_length=100)),
                ('type_of_tool', models.CharField(blank=True, max_length=30, null=True)),
                ('reason', models.CharField(max_length=100, null=True)),
                ('drawings_2d', models.FileField(blank=True, max_length=300, null=True, upload_to='drawings_2d')),
                ('drawings_3d', models.FileField(blank=True, max_length=300, null=True, upload_to='drawings_3d')),
                ('screen_catalog', models.FileField(blank=True, max_length=300, null=True, upload_to='screen_catalog')),
                ('comments', models.TextField(blank=True, max_length=1000, null=True)),
                ('entry_date', models.DateTimeField(auto_now=True)),
                ('change_date', models.DateTimeField(blank=True, null=True)),
                ('entry_employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entry_employee_data', to='PWRKapp.employee')),
                ('manage_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manage_employee_data', to='PWRKapp.employee')),
                ('producer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='producer_data', to='PWRKapp.producersupplier')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_data', to='PWRKapp.producersupplier')),
            ],
        ),
    ]
