# Generated by Django 5.1.3 on 2024-12-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PWRKapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='description_1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='reason',
            field=models.CharField(choices=[('choice1', 'Nowe narzędzie - nowe uruchomienie'), ('choice2', 'Nowe narzędzie - optymalizacja'), ('choice3', 'Brak pwrk / Inwentaryzacja')], default='choice1', max_length=100),
        ),
        migrations.AddField(
            model_name='entry',
            name='type_of_employee',
            field=models.CharField(choices=[('choice1', 'Pracownik wypożyczalni'), ('choice2', 'Technolog')], max_length=30, null=True),
        ),
    ]
