# Generated by Django 5.1.3 on 2024-12-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PWRKapp', '0002_entry_description_1_entry_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='type_of_employee',
            field=models.BooleanField(choices=[('choice1', 'Pracownik wypożyczalni'), ('choice2', 'Technolog')], null=True),
        ),
    ]
