# Generated by Django 5.1.3 on 2024-12-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PWRKapp', '0004_alter_entry_type_of_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='type_of_employee',
            field=models.CharField(choices=[('choice1', 'Pracownik wypożyczalni'), ('choice2', 'Technolog')], max_length=100),
        ),
    ]
