# Generated by Django 5.1.3 on 2024-12-12 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PWRKapp', '0007_entry_type_of_tool_alter_entry_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('admin_access', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='comments',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='drawings_2d',
            field=models.FileField(null=True, upload_to='drawings_2d'),
        ),
        migrations.AddField(
            model_name='entry',
            name='drawings_3d',
            field=models.FileField(null=True, upload_to='drawings_3d'),
        ),
        migrations.AddField(
            model_name='entry',
            name='producer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='supplier',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='entry_employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='PWRKapp.employee'),
        ),
    ]
