# Generated by Django 5.1.3 on 2024-12-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PWRKapp', '0013_alter_entry_drawings_2d_alter_entry_drawings_3d'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='drawings_2d',
            field=models.FileField(null=True, upload_to='drawings_2d'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='drawings_3d',
            field=models.FileField(null=True, upload_to='drawings_3d'),
        ),
    ]
