# Generated by Django 5.1.3 on 2024-12-13 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PWRKapp', '0017_alter_entry_producer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='producer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='producer_data', to='PWRKapp.producersupplier'),
        ),
    ]
