# Generated by Django 5.1.3 on 2024-12-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PWRKapp', '0018_alter_entry_producer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='producer',
            field=models.CharField(max_length=100),
        ),
    ]
