# Generated by Django 5.1.3 on 2024-12-13 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PWRKapp', '0020_alter_entry_producer'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='entry_status',
            field=models.CharField(default='Nowy', max_length=30),
        ),
    ]
