# Generated by Django 5.1.3 on 2024-12-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PWRKapp', '0021_entry_entry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='PWRK',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
