# Generated by Django 5.1.3 on 2024-12-13 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PWRKapp', '0022_entry_pwrk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='entry_status',
            field=models.CharField(blank=True, db_default='Nowy', max_length=30),
        ),
    ]
