# Generated by Django 5.1.3 on 2024-12-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PWRKapp', '0024_alter_entry_entry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='catalog_screen',
            field=models.FileField(null=True, upload_to='catalog_screen'),
        ),
        migrations.AddField(
            model_name='entry',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
