# Generated by Django 5.1.3 on 2024-12-13 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PWRKapp', '0025_entry_catalog_screen_entry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='catalog_screen',
        ),
        migrations.AddField(
            model_name='entry',
            name='screen_catalog',
            field=models.FileField(null=True, upload_to='screen_catalog'),
        ),
    ]
