# Generated by Django 5.1.3 on 2024-12-13 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PWRKapp', '0026_remove_entry_catalog_screen_entry_screen_catalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='drawings_2d',
            field=models.FileField(max_length=300, null=True, upload_to='drawings_2d'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='drawings_3d',
            field=models.FileField(max_length=300, null=True, upload_to='drawings_3d'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='screen_catalog',
            field=models.FileField(max_length=300, null=True, upload_to='screen_catalog'),
        ),
    ]
