# Generated by Django 5.1.3 on 2024-12-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PWRKapp', '0027_alter_entry_drawings_2d_alter_entry_drawings_3d_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='type_of_tool',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
