# Generated by Django 5.1.3 on 2024-12-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PWRKapp', '0028_alter_entry_type_of_tool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='comments',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='drawings_2d',
            field=models.FileField(blank=True, max_length=300, null=True, upload_to='drawings_2d'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='drawings_3d',
            field=models.FileField(blank=True, max_length=300, null=True, upload_to='drawings_3d'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='screen_catalog',
            field=models.FileField(blank=True, max_length=300, null=True, upload_to='screen_catalog'),
        ),
    ]
