# Generated by Django 5.1.3 on 2024-12-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PWRKapp', '0029_alter_entry_comments_alter_entry_drawings_2d_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
