# Generated by Django 5.1.3 on 2024-12-14 14:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PWRKapp', '0030_alter_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 14, 14, 30, 47, 174614, tzinfo=datetime.timezone.utc)),
        ),
    ]
