# Generated by Django 5.1.3 on 2024-12-15 22:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PWRKapp', '0036_alter_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 12, 15, 22, 22, 11, 122620, tzinfo=datetime.timezone.utc)),
        ),
    ]
