# Generated by Django 5.1.3 on 2024-12-16 00:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PWRKapp', '0039_alter_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='drawings_2d',
            field=models.FileField(blank=True, max_length=300, null=True, upload_to='drawings_2d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
