# Generated by Django 5.1.3 on 2024-12-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PWRKapp', '0041_alter_entry_drawings_2d'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='reason',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
