# Generated by Django 5.1.3 on 2024-12-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PWRKapp', '0042_alter_entry_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='aplication_access',
            field=models.BooleanField(null=True),
        ),
    ]
