# Generated by Django 5.1.3 on 2024-12-16 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PWRKapp', '0043_employee_aplication_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='entry_employee',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='PWRKapp.employee'),
        ),
    ]
