# Generated by Django 5.1.3 on 2024-12-16 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PWRKapp', '0044_alter_entry_entry_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='manage_employee',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manage_employee_data', to='PWRKapp.employee'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_employee',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entry_employee_data', to='PWRKapp.employee'),
        ),
    ]
