# Generated by Django 5.1.3 on 2024-12-16 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PWRKapp', '0045_entry_manage_employee_alter_entry_entry_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='entry_status',
            new_name='status',
        ),
    ]
