# Generated by Django 5.1.3 on 2024-12-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PWRKapp', '0047_rename_date_entry_change_date_entry_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='change_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
