# Generated by Django 5.1.3 on 2024-12-16 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PWRKapp', '0048_alter_entry_change_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='manage_employee',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manage_employee_data', to='PWRKapp.employee'),
        ),
    ]
