# Generated by Django 5.1.3 on 2024-12-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PWRKapp', '0049_alter_entry_manage_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='change_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
