# Generated by Django 5.1.3 on 2024-12-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PWRKapp', '0050_alter_entry_change_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(blank=True, default='NOWY', max_length=30),
        ),
    ]
