# Generated by Django 5.1.3 on 2024-12-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PWRKapp', '0051_alter_entry_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='comments',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
