# Generated by Django 5.1.3 on 2025-01-07 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PWRKapp', '0052_alter_entry_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='PWRK',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
